/**
 * THE LINK REACTION — 2D / Semi-2D Application Controller
 * Manages the Bottom Process Bar, 8-stage narrative progression,
 * Core/Deeper tiers, and carbon tracker.
 */

import { init2DScene, render2DStage, replayCurrentStageAnimation, toggleAll2DLabels, getStageFocusName } from './scene2d.js?v=14';

// =============================================================================
// 1. COMPREHENSIVE EDUCATIONAL DATABASE (STAGES 00 - 07)
// =============================================================================

export const STAGES_DATA = [
  {
    id: 0,
    number: "00 / 07",
    shortName: "Arrival",
    iconLabel: "Mito",
    title: "Arrival at the Mitochondrion",
    conceptHeadline: "The molecular bridge between glycolysis and the Krebs cycle.",
    compartment: "Cytosol / Outer Membrane",
    nature: "Preparatory",
    where: "Cytosol bordering the outer mitochondrial membrane. The outer membrane is freely permeable to small metabolites, allowing direct diffusion into the intermembrane space.",
    what: "Pyruvate (3C), the end-product of cytoplasmic glycolysis, approaches the mitochondrion to begin aerobic respiration. Two pyruvate molecules arrive per glucose metabolized.",
    how: "Small metabolites diffuse passively across the permeable outer membrane. Cytosolic thermal motion directs the negatively charged pyruvate molecules toward the envelope.",
    why: "Forms the crucial cellular bridge linking cytoplasmic glycolysis to the matrix-based Krebs cycle. Without compartmental entry, pyruvate cannot access the pyruvate dehydrogenase enzyme machinery required for complete aerobic oxidation.",
    moleculesInFocus: ["pyruvate", "outer_membrane"],
    carbonState: {
      status: "3C (Pyruvate)",
      beads: ["active", "active", "active"]
    },
    deeper: {
      enzymology: "Glycolysis ends in the cytoplasm with 2 pyruvate molecules per glucose. The outer mitochondrial membrane allows passive diffusion of small molecules under 5,000 Daltons into the intermembrane space.",
      mechanism: "Pyruvate is an alpha-keto acid (CH₃-CO-COO⁻) with a net negative charge at physiological pH (7.2–7.4), allowing it to traverse the permeable outer membrane.",
      regulation: "If cellular oxygen is depleted, pyruvate cannot proceed through the link reaction; instead, it is diverted to lactate dehydrogenase in animals (fermentation) to regenerate NAD⁺.",
      simplificationNote: "The outer membrane is permeable to small molecules, but the inner membrane is an impermeable barrier that requires specific carrier proteins."
    }
  },
  {
    id: 1,
    number: "01 / 07",
    shortName: "Matrix Entry",
    iconLabel: "Entry",
    title: "Entry into the Matrix",
    conceptHeadline: "Crossing the impermeable inner membrane into the reaction chamber.",
    compartment: "Inner Membrane & Matrix",
    nature: "Active Transport",
    where: "Across the inner mitochondrial membrane, whose extensive inward folds are called cristae, into the matrix. The inner membrane maintains a strict electrochemical gradient essential for ATP synthesis.",
    what: "Pyruvate is transported from the intermembrane space into the soluble mitochondrial matrix chamber. This delivers the substrate directly to where link reaction enzymes reside.",
    how: "The Mitochondrial Pyruvate Carrier (MPC) transports pyruvate across the inner membrane via proton-coupled symport. Transport is driven down the proton concentration gradient generated by the respiratory chain.",
    why: "Enables selective substrate delivery while strictly preserving the vital chemiosmotic proton gradient across the cristae. This prevents uncontrolled proton leakage that would uncouple and collapse cellular ATP production.",
    moleculesInFocus: ["pyruvate", "mpc"],
    carbonState: {
      status: "3C (Entering Matrix)",
      beads: ["active", "active", "active"]
    },
    deeper: {
      enzymology: "The MPC is an obligate heterodimer of MPC1 and MPC2 proteins located in the inner membrane. It operates as a pyruvate⁻ / H⁺ symporter.",
      mechanism: "The electron transport chain pumps H⁺ ions into the intermembrane space, creating a membrane potential (~-180 mV) and pH gradient (pH ~8.0 in matrix vs 7.2 in IMS). Pyruvate import is energetically coupled to this electrochemical gradient.",
      regulation: "MPC activity is a key regulatory bottleneck. In cancer cells (Warburg effect), MPC is frequently downregulated, trapping pyruvate in the cytosol to drive aerobic glycolysis.",
      simplificationNote: "Many general textbooks omit the MPC and simply state 'pyruvate enters via active transport'."
    }
  },
  {
    id: 2,
    number: "02 / 07",
    shortName: "PDC Complex",
    iconLabel: "PDC",
    title: "Meeting the Pyruvate Dehydrogenase Complex",
    conceptHeadline: "A colossal macromolecular machine coordinating the link reaction.",
    compartment: "Mitochondrial Matrix",
    nature: "Enzyme Assembly",
    where: "Soluble mitochondrial matrix reaction space. The colossal Pyruvate Dehydrogenase Complex (PDC) operates suspended in this concentrated aqueous environment.",
    what: "Pyruvate docks at the catalytic active sites of the Pyruvate Dehydrogenase Complex. This multi-enzyme assembly coordinates decarboxylation, oxidation, and CoA coupling in rapid sequence.",
    how: "Multiple catalytic centers are grouped into a single unified macromolecular assembly. Direct intermediate channeling transfers substrates directly between adjacent active sites without leakage into the matrix.",
    why: "Greatly accelerates catalytic reaction rates while protecting unstable reaction intermediates from competing side-reactions. It functions as the primary regulatory gateway directing carbohydrates into aerobic respiration.",
    moleculesInFocus: ["pdc", "pyruvate"],
    carbonState: {
      status: "3C (Docked at PDC)",
      beads: ["active", "active", "active"]
    },
    deeper: {
      enzymology: "The Pyruvate Dehydrogenase Complex (PDC) is a multi-enzyme machine in the matrix with a mass exceeding 9 million Daltons. It groups the catalytic machinery together so that substrates and intermediates are processed with maximal efficiency.",
      mechanism: "The complex coordinates three substrates (pyruvate, Coenzyme A, and NAD⁺) to generate three products (acetyl-CoA, CO₂, and NADH + H⁺). All intermediate fragments remain within the complex throughout the catalytic cycle.",
      regulation: "PDC is tightly controlled. Inactivated by Pyruvate Dehydrogenase Kinase (PDK) in response to high energy states (high ATP, NADH, Acetyl-CoA). Activated by Pyruvate Dehydrogenase Phosphatase (PDP) in response to high ADP, pyruvate, and Ca²⁺.",
      simplificationNote: "The PDC operates as a unified multi-enzyme complex in the mitochondrial matrix, acting as the primary gateway into aerobic cellular respiration."
    }
  },
  {
    id: 3,
    number: "03 / 07",
    shortName: "Decarboxylation",
    iconLabel: "–CO₂",
    title: "Decarboxylation: Carbon Leaves",
    conceptHeadline: "The loss of the first carbon atom in cellular respiration as CO₂.",
    compartment: "PDC Active Site",
    nature: "Decarboxylation",
    where: "Active site cavity of the Pyruvate Dehydrogenase Complex in the mitochondrial matrix.",
    what: "Pyruvate (3C) loses its terminal carboxyl group, releasing the very first molecule of CO₂ in cellular respiration. This cleaves the 3-carbon skeleton down to an enzyme-bound 2-carbon hydroxyethyl fragment.",
    how: "Catalytic decarboxylation cleaves the carbon-carbon bond holding the carboxyl group, liberating carbon dioxide gas. The volatile CO₂ molecule diffuses away while the remaining 2-carbon fragment remains tethered for oxidation.",
    why: "Reduces the carbon chain length from 3 carbons to 2 carbons to match the acceptor molecule in the Krebs cycle. Rapid diffusion of CO₂ gas out of the matrix makes this step physiologically irreversible in living cells.",
    moleculesInFocus: ["pyruvate", "co2"],
    carbonState: {
      status: "2C Fragment + 1C CO₂",
      beads: ["detached", "active", "active"]
    },
    deeper: {
      enzymology: "Decarboxylation is the initial step of the link reaction. The PDC specifically targets the carboxyl group of pyruvate, converting a 3-carbon intermediate into a 2-carbon unit.",
      mechanism: "CO₂ gas is released from pyruvate, leaving a 2-carbon acetyl group retained within the active site of the complex for immediate oxidation.",
      regulation: "The release of CO₂ gas and large negative free energy make this reaction physiologically irreversible in vivo.",
      simplificationNote: "CO₂ is a non-polar gas that diffuses freely out of the mitochondrial matrix, across the inner and outer membranes, into the cytosol, and into the bloodstream."
    }
  },
  {
    id: 4,
    number: "04 / 07",
    shortName: "Oxidation",
    iconLabel: "Redox",
    title: "Oxidation: Transfer of Electrons to NAD⁺",
    conceptHeadline: "Harvesting high-energy electrons to reduce NAD⁺ into NADH.",
    compartment: "PDC Active Site",
    nature: "Redox Reaction",
    where: "Catalytic active site of the Pyruvate Dehydrogenase Complex within the mitochondrial matrix.",
    what: "The 2-carbon fragment is oxidized to an acetyl group while NAD⁺ is reduced to NADH and H⁺. Notably, zero ATP is synthesized directly during this oxidation step.",
    how: "Dehydrogenase active sites extract a pair of high-energy electrons and two protons from the 2-carbon substrate. Two electrons and one proton are transferred to NAD⁺ to yield NADH, releasing one free proton (H⁺) into the matrix pool.",
    why: "Harvests high-energy electrons into the mobile carrier NADH to fuel the electron transport chain on the cristae. Each NADH produced will subsequently yield approximately 2.5 ATP via oxidative phosphorylation.",
    moleculesInFocus: ["nad", "nadh", "h_plus"],
    carbonState: {
      status: "2C (Oxidized) + NADH",
      beads: ["detached", "active", "active"]
    },
    deeper: {
      enzymology: "Dehydrogenase activity within the PDC catalyzes the oxidation of the 2-carbon fragment, directly coupling the release of electrons to the reduction of NAD⁺.",
      mechanism: "NAD⁺ accepts two electrons and one proton (a hydride ion, :H⁻), reducing to NADH, while a second proton (H⁺) is released into the matrix proton pool.",
      regulation: "High matrix [NADH]/[NAD⁺] ratio strongly inhibits the PDC via competitive product inhibition, signaling that downstream electron transport is saturated.",
      simplificationNote: "Remember: NADH is an electron shuttle, not an ATP molecule. It will yield ATP later when its electrons are donated to the electron transport chain on the inner mitochondrial membrane."
    }
  },
  {
    id: 5,
    number: "05 / 07",
    shortName: "Acetyl-CoA",
    iconLabel: "CoA",
    title: "Formation of Acetyl-CoA",
    conceptHeadline: "Coupling the 2-carbon acetyl group to Coenzyme A via a high-energy thioester bond.",
    compartment: "PDC Active Site",
    nature: "Thioester Synthesis",
    where: "Catalytic active site of the Pyruvate Dehydrogenase Complex within the mitochondrial matrix.",
    what: "The oxidized 2-carbon acetyl group is transferred onto Coenzyme A, completing the link reaction as Acetyl-CoA. This successfully yields the central substrate required for the Krebs cycle.",
    how: "The acetyl fragment couples to the reactive terminal thiol (-SH) sulfhydryl group of Coenzyme A. This condensation creates an energy-rich carbon-sulfur thioester bond that preserves the free energy released during oxidation.",
    why: "Energizes the 2-carbon acetyl unit with high group-transfer potential for condensation into the Krebs cycle. This allows Acetyl-CoA to spontaneously combine with 4-carbon oxaloacetate to form 6-carbon citrate.",
    moleculesInFocus: ["coa", "acetyl_coa"],
    carbonState: {
      status: "2C-S-CoA (Acetyl-CoA)",
      beads: ["detached", "acetyl", "acetyl"]
    },
    deeper: {
      enzymology: "Coenzyme A consists of a 3'-phosphoadenosine diphosphate linked to pantothenate (vitamin B5) and beta-mercaptoethylamine. The reactive business end is the terminal sulfhydryl / thiol group (-SH).",
      mechanism: "The PDC transfers the acetyl group to the reactive sulfur of CoA-SH, forming a high-energy thioester bond (C–S–CoA) that preserves the energy released during oxidation.",
      regulation: "Acetyl-CoA exerts potent product inhibition on the PDC. It also acts as an allosteric activator of pyruvate carboxylase.",
      simplificationNote: "Because sulfur does not form effective pi-bonds with carbon, thioesters lack the resonance stabilization of oxygen esters. This gives the thioester bond its high chemical transfer potential."
    }
  },
  {
    id: 6,
    number: "06 / 07",
    shortName: "Complete Equation",
    iconLabel: "Eq.",
    title: "The Balanced Equation & Stoichiometry",
    conceptHeadline: "Resolving per-pyruvate versus per-glucose yields.",
    compartment: "Mitochondrial Matrix Chamber",
    nature: "Quantitative Yield",
    where: "Mitochondrial matrix reaction space, accounting for all inputs and outputs across the link reaction.",
    what: "Pyruvate + CoA + NAD⁺ → Acetyl-CoA + CO₂ + NADH + H⁺. Because glycolysis splits each glucose into two pyruvates, whole-cell yields double per original glucose molecule.",
    how: "Operating twice per glucose, the link reaction consumes 2 pyruvates, 2 CoA, and 2 NAD⁺ to produce 2 Acetyl-CoA, 2 CO₂, and 2 NADH + 2 H⁺. The reaction has a large negative standard free energy change (ΔG°' = -33.4 kJ/mol).",
    why: "Provides rigorous stoichiometric accounting of energy capture and carbon flux entering aerobic metabolism. The 2 NADH will yield ~5 ATP via oxidative phosphorylation, while 2 Acetyl-CoA enter the Krebs cycle to produce another ~20 ATP equivalents.",
    moleculesInFocus: ["pyruvate", "coa", "nad", "acetyl_coa", "co2", "nadh"],
    carbonState: {
      status: "Complete Equation Balance",
      beads: ["detached", "acetyl", "acetyl"]
    },
    deeper: {
      enzymology: "Standard free energy change: ΔG°' = -33.4 kJ/mol. The large negative free energy and loss of volatile CO₂ gas makes this reaction physiologically irreversible in vivo. Animals cannot convert acetyl-CoA into pyruvate or glucose.",
      mechanism: "Carbon balance: 3C (Pyruvate) = 2C (Acetyl-CoA) + 1C (CO₂). Redox balance: NAD⁺ + 2e⁻ + 2H⁺ → NADH + H⁺. Energy balance: 0 ATP directly, but the 2 NADH generated will yield ~5 ATP via oxidative phosphorylation.",
      regulation: "PDC is the central commitment point in animal metabolism: once pyruvate passes this gate, the carbons are destined either for complete oxidation in the Krebs cycle or for fatty acid synthesis.",
      simplificationNote: "Always check whether an exam question specifies 'per pyruvate' (1 Acetyl-CoA, 1 CO₂, 1 NADH) or 'per glucose' (2 Acetyl-CoA, 2 CO₂, 2 NADH)."
    }
  },
  {
    id: 7,
    number: "07 / 07",
    shortName: "Respiration Map",
    iconLabel: "Map",
    title: "Where This Sits in Respiration",
    conceptHeadline: "The master metabolic map connecting all four stages of cellular respiration.",
    compartment: "Whole Mitochondrion & Cytosol",
    nature: "Metabolic Integration",
    where: "Mitochondrial matrix, physically and functionally bridging cytosolic glycolysis with the inner membrane cristae.",
    what: "Functions as the central metabolic hub integrating glycolysis (Stage 1) with the Krebs cycle (Stage 3) and oxidative phosphorylation (Stage 4).",
    how: "Delivers Acetyl-CoA directly to matrix citrate synthase in the Krebs cycle while routing generated NADH to Complex I of the respiratory chain on the inner membrane cristae.",
    why: "Operates as the master irreversible commitment point governing carbohydrate breakdown in aerobic respiration. If oxygen is absent, respiratory chain electron transport halts, NADH accumulates, and the link reaction is completely shut down.",
    moleculesInFocus: ["acetyl_coa", "nadh"],
    carbonState: {
      status: "Respiration Network Context",
      beads: ["detached", "acetyl", "acetyl"]
    },
    deeper: {
      enzymology: "The link reaction and Krebs cycle share the same compartment (matrix) which prevents dilution of Acetyl-CoA and maintains high local substrate concentrations for Citrate Synthase.",
      mechanism: "CO₂ produced by the link reaction (and Krebs cycle) is non-polar and diffuses freely out of the mitochondrion, into the capillaries, to be exhaled by the lungs.",
      regulation: "If oxygen is unavailable, the electron transport chain halts, NADH and FADH₂ accumulate, matrix NAD⁺ is depleted, and both the Krebs cycle and Link Reaction shut down completely.",
      simplificationNote: "Although taught as distinct chapters in textbooks, in a living cell these four stages operate simultaneously and in direct physical proximity."
    }
  }
];

// =============================================================================
// 2. MOLECULE INSPECTOR DATABASE
// =============================================================================

export const MOLECULES_DATA = {
  pyruvate: {
    name: "Pyruvate (Pyruvic Acid)",
    formula: "C₃H₃O₃⁻ • 87.05 g/mol",
    category: "Substrate Metabolite",
    carbons: 3,
    diagram: `  O     O
  ||    ||
  C  -  C  -  CH₃
  |
  O⁻`,
    role: "The 3-carbon carboxylate end-product of glycolysis. Formed in the cytoplasm, it must cross both mitochondrial membranes into the matrix to enter aerobic respiration.",
    fate: "Decarboxylated by the PDC to release CO₂ and leave a 2-carbon acetyl fragment.",
    alert: "Glycolysis produces 2 pyruvate molecules per glucose. Hence, 2 link reactions occur for every glucose molecule consumed."
  },
  coa: {
    name: "Coenzyme A (CoA-SH)",
    formula: "C₂₁H₃₆N₇O₁₆P₃S • 767.53 g/mol",
    category: "Carrier Coenzyme",
    carbons: 0,
    diagram: `ADP-3'P -- Pantothenate -- Cysteamine -- SH (Thiol)`,
    role: "A universal carrier of acyl groups in all living organisms. Derived from pantothenic acid (Vitamin B5).",
    fate: "Its terminal thiol (-SH) accepts the 2-carbon acetyl fragment at the PDC active site, forming an energy-rich thioester bond in Acetyl-CoA.",
    alert: "The thioester bond has a high negative standard free energy of hydrolysis (ΔG°' = -31.5 kJ/mol), which provides the driving force for the subsequent Krebs cycle."
  },
  nad: {
    name: "NAD⁺ (Nicotinamide Adenine Dinucleotide)",
    formula: "C₂₁H₂₇N₇O₁₄P₂ • 663.43 g/mol",
    category: "Oxidized Electron Carrier",
    carbons: 0,
    diagram: `Nicotinamide+ - Ribose - Pyrophosphate - Adenosine`,
    role: "The primary oxidized coenzyme electron acceptor of catabolic metabolism. Derived from niacin (Vitamin B3).",
    fate: "Accepts 2 electrons and 1 proton (hydride ion :H⁻) from the oxidation reaction catalyzed by the PDC, becoming reduced to NADH, while releasing 1 proton (H⁺) into the matrix.",
    alert: "NAD⁺ is strictly an electron shuttle, NOT ATP. It must be regenerated by the electron transport chain or fermentation."
  },
  nadh: {
    name: "NADH (Reduced Carrier)",
    formula: "C₂₁H₂₉N₇O₁₄P₂ • 665.44 g/mol",
    category: "Reduced Electron Carrier",
    carbons: 0,
    diagram: `Nicotinamide-H (Reduced) -- Dinucleotide Backbone`,
    role: "Carries 2 high-energy electrons extracted from the oxidation of the 2-carbon fragment.",
    fate: "Diffuses to the inner mitochondrial membrane where it donates its electrons to Complex I of the Electron Transport Chain, powering proton pumping.",
    alert: "CRITICAL SYLLABUS RULE: No ATP is generated directly in the link reaction! Each NADH produced will yield ~2.5 ATP downstream in oxidative phosphorylation."
  },
  acetyl_coa: {
    name: "Acetyl-Coenzyme A",
    formula: "C₂₃H₃₈N₇O₁₇P₃S • 809.57 g/mol",
    category: "Activated Product",
    carbons: 2,
    diagram: `       O
       ||
CH₃ - C - S - CoA`,
    role: "The primary output of the link reaction. Represents the activated 2-carbon unit ready for combustion in the Krebs cycle.",
    fate: "Leaves the PDC and enters the Krebs cycle, where its acetyl group condenses with 4-carbon oxaloacetate to form 6-carbon citrate.",
    alert: "Irreversible formation: In mammals, Acetyl-CoA cannot be converted back to pyruvate or carbohydrates because the PDC reaction is thermodynamically irreversible."
  },
  co2: {
    name: "Carbon Dioxide (CO₂)",
    formula: "CO₂ • 44.01 g/mol",
    category: "Gaseous Waste Product",
    carbons: 1,
    diagram: `O = C = O`,
    role: "The first molecule of carbon dioxide released during cellular respiration.",
    fate: "As a small non-polar gas, CO₂ diffuses freely through the mitochondrial membranes, into the cytoplasm, and into the bloodstream to be expired.",
    alert: "A common exam misconception is that all CO₂ comes from the Krebs cycle. In fact, 2 of the 6 CO₂ molecules produced per glucose originate right here in the Link Reaction!"
  },
  h_plus: {
    name: "Proton (H⁺)",
    formula: "H⁺ • 1.008 g/mol",
    category: "Hydronium Ion",
    carbons: 0,
    diagram: `[ H⁺ ]`,
    role: "Co-product released into the mitochondrial matrix alongside NADH during the reduction of NAD⁺.",
    fate: "Enters the matrix proton pool and can be utilized by downstream metabolic reactions.",
    alert: "The reaction stoichiometry is: NAD⁺ + 2e⁻ + 2H⁺ → NADH + H⁺."
  },
  pdc: {
    name: "Pyruvate Dehydrogenase Complex (PDC)",
    formula: "Multi-enzyme Complex (~9.5 MDa)",
    category: "Macromolecular Enzyme Complex",
    carbons: 0,
    diagram: `[ Pyruvate + CoA + NAD⁺ ] ---> [ PDC ] ---> [ Acetyl-CoA + CO₂ + NADH + H⁺ ]`,
    role: "A colossal multi-enzyme machine in the mitochondrial matrix that coordinates the reactions of the link reaction.",
    fate: "Catalyzes oxidative decarboxylation: removes CO₂, transfers electrons to NAD⁺ to form NADH, and couples the remaining acetyl group to Coenzyme A.",
    alert: "By uniting these reactions into a single complex, intermediate products are directly channeled, maximizing reaction rate and metabolic efficiency."
  },
  mpc: {
    name: "Mitochondrial Pyruvate Carrier (MPC)",
    formula: "MPC1 / MPC2 Heterodimer",
    category: "Inner Membrane Transporter",
    carbons: 0,
    diagram: `Outer |--- Inner Membrane Transporter ---| Matrix (H⁺ Symport)`,
    role: "Facilitates proton-coupled pyruvate transport across the otherwise impermeable inner mitochondrial membrane.",
    fate: "Couples pyruvate entry to the proton gradient established by the electron transport chain.",
    alert: "Without the MPC, cytosolic pyruvate cannot reach the matrix PDC."
  },
  outer_membrane: {
    name: "Outer Mitochondrial Membrane",
    formula: "Phospholipid Bilayer (~6–7 nm)",
    category: "Mitochondrial Boundary",
    carbons: 0,
    diagram: `Cytosol |=== Outer Membrane Bilayer ===| Intermembrane Space`,
    role: "Forms the smooth outer boundary of the mitochondrion, separating organellar compartments from the cytosol.",
    fate: "Freely permeable to small molecules (<5 kDa), enabling rapid exchange of nutrients and metabolites.",
    alert: "Unlike the tightly sealed inner membrane, the outer membrane is freely permeable to small solutes."
  }
};

// =============================================================================
// 3. APPLICATION STATE
// =============================================================================

export const state = {
  currentStage: 0,
  showAllLabels: false,
  perGlucoseMode: false,
  isDeeperOpen: false
};

// =============================================================================
// 4. UI INITIALIZATION & EVENT LISTENERS
// =============================================================================

function startApp() {
  initHeaderHeightTracker();
  initHeaderScroll();
  initBottomProcessBar();
  bindUIEvents();
  renderStage(state.currentStage);
  init2DScene();

  // Listen for custom inspect-molecule event dispatched by 2D scene
  document.addEventListener('inspect-molecule', (e) => {
    if (e.detail) openMoleculeModal(e.detail);
  });
}

export function updateHeaderScrollCues() {
  const header = document.querySelector('.hud-header');
  if (!header) return;
  const maxScroll = header.scrollWidth - header.clientWidth;
  if (maxScroll <= 2) {
    header.classList.remove('can-scroll-left', 'can-scroll-right');
    return;
  }
  const isLeft = header.scrollLeft > 4;
  const isRight = header.scrollLeft < maxScroll - 4;
  header.classList.toggle('can-scroll-left', isLeft);
  header.classList.toggle('can-scroll-right', isRight);
}

function initHeaderScroll() {
  const header = document.querySelector('.hud-header');
  if (!header) return;

  header.addEventListener('scroll', updateHeaderScrollCues, { passive: true });
  window.addEventListener('resize', updateHeaderScrollCues, { passive: true });
  if (document.fonts) document.fonts.ready.then(updateHeaderScrollCues);
  setTimeout(updateHeaderScrollCues, 150);

  // Mouse Click-and-Drag Scrolling
  let isDown = false;
  let startX = 0;
  let scrollLeft = 0;
  let isDragging = false;

  header.addEventListener('mousedown', (e) => {
    if (e.button !== 0) return;
    isDown = true;
    startX = e.pageX - header.offsetLeft;
    scrollLeft = header.scrollLeft;
    isDragging = false;
  });

  window.addEventListener('mousemove', (e) => {
    if (!isDown) return;
    const x = e.pageX - header.offsetLeft;
    const walk = x - startX;
    if (Math.abs(walk) > 3) {
      isDragging = true;
      header.classList.add('is-dragging');
    }
    if (isDragging) {
      e.preventDefault();
      header.scrollLeft = scrollLeft - walk;
    }
  });

  const stopDrag = () => {
    if (!isDown) return;
    isDown = false;
    setTimeout(() => {
      header.classList.remove('is-dragging');
    }, 50);
  };

  window.addEventListener('mouseup', stopDrag);

  // Prevent accidental clicks on child buttons if mouse was dragged
  header.addEventListener('click', (e) => {
    if (isDragging) {
      e.preventDefault();
      e.stopPropagation();
      isDragging = false;
    }
  }, true);

  // Translate vertical wheel to horizontal scroll if over header and scrollable
  header.addEventListener('wheel', (e) => {
    if (Math.abs(e.deltaY) > Math.abs(e.deltaX) && header.scrollWidth > header.clientWidth) {
      e.preventDefault();
      header.scrollLeft += e.deltaY;
    }
  }, { passive: false });
}

function initHeaderHeightTracker() {
  syncHeaderHeight();
  if (window.ResizeObserver) {
    const headerEl = document.querySelector('.hud-header');
    if (headerEl) {
      new ResizeObserver(() => syncHeaderHeight()).observe(headerEl);
    }
  }
  if (document.fonts) {
    document.fonts.ready.then(syncHeaderHeight);
  }
  window.addEventListener('resize', syncHeaderHeight);
}

export function syncHeaderHeight() {
  const header = document.querySelector('.hud-header');
  if (header) {
    document.documentElement.style.setProperty('--hud-header-h', `${header.offsetHeight}px`);
  }
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', startApp);
} else {
  startApp();
}

function bindUIEvents() {
  // Navigation Buttons on Card
  const btnPrev = document.getElementById('btn-prev-stage');
  const btnNext = document.getElementById('btn-next-stage');
  
  btnPrev?.addEventListener('click', () => {
    if (state.currentStage > 0) goToStage(state.currentStage - 1);
  });

  btnNext?.addEventListener('click', () => {
    if (state.currentStage < STAGES_DATA.length - 1) goToStage(state.currentStage + 1);
  });

  // Arrow buttons on bottom process bar
  const btnBarPrev = document.getElementById('btn-process-prev');
  const btnBarNext = document.getElementById('btn-process-next');
  btnBarPrev?.addEventListener('click', () => {
    if (state.currentStage > 0) goToStage(state.currentStage - 1);
  });
  btnBarNext?.addEventListener('click', () => {
    if (state.currentStage < STAGES_DATA.length - 1) goToStage(state.currentStage + 1);
  });

  // Replay animation button
  const btnReplay = document.getElementById('btn-replay-scene');
  btnReplay?.addEventListener('click', () => {
    replayCurrentStageAnimation();
  });

  // Keyboard navigation (Arrow keys Left / Right)
  window.addEventListener('keydown', (e) => {
    // If modal open, escape closes it
    const molModal = document.getElementById('molecule-modal-backdrop');
    if (molModal && !molModal.hidden) {
      if (e.key === 'Escape') closeMoleculeModal();
      return;
    }

    if (e.key === 'ArrowRight' || e.key === 'ArrowDown' || e.key === 'PageDown') {
      if (state.currentStage < STAGES_DATA.length - 1) goToStage(state.currentStage + 1);
    } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp' || e.key === 'PageUp') {
      if (state.currentStage > 0) goToStage(state.currentStage - 1);
    } else if (e.key === 'l' || e.key === 'L') {
      toggleLabels();
    } else if (e.key === 'r' || e.key === 'R') {
      replayCurrentStageAnimation();
    }
  });

  // Touch swipe support for mobile (scoped strictly to 2D scene stage area)
  const stageArea = document.getElementById('scene-stage-area');
  let touchStartX = 0;
  let touchEndX = 0;
  let touchStartY = 0;
  let touchEndY = 0;
  stageArea?.addEventListener('touchstart', (e) => {
    touchStartX = e.changedTouches[0].screenX;
    touchStartY = e.changedTouches[0].screenY;
  }, { passive: true });

  stageArea?.addEventListener('touchend', (e) => {
    touchEndX = e.changedTouches[0].screenX;
    touchEndY = e.changedTouches[0].screenY;
    handleSwipe();
  }, { passive: true });

  function handleSwipe() {
    const diffX = touchStartX - touchEndX;
    const diffY = touchStartY - touchEndY;
    // Only trigger if horizontal movement is dominant and exceeds threshold
    if (Math.abs(diffX) > 50 && Math.abs(diffX) > Math.abs(diffY) * 1.5) {
      if (diffX > 0 && state.currentStage < STAGES_DATA.length - 1) {
        goToStage(state.currentStage + 1); // Swipe left = next
      } else if (diffX < 0 && state.currentStage > 0) {
        goToStage(state.currentStage - 1); // Swipe right = prev
      }
    }
  }

  // Toggle "Show All Labels" (§8)
  const btnToggleLabels = document.getElementById('btn-toggle-labels');
  btnToggleLabels?.addEventListener('click', toggleLabels);

  // Toggle "Per Glucose (x2)" (§5)
  const btnToggleGlucose = document.getElementById('btn-toggle-glucose');
  btnToggleGlucose?.addEventListener('click', toggleGlucoseYield);

  // Deeper Accordion Toggle
  const btnDeeper = document.getElementById('btn-deeper-toggle');
  btnDeeper?.addEventListener('click', toggleDeeperAccordion);

  // Close Molecule Modal
  const btnCloseMol = document.getElementById('btn-close-mol-modal');
  const modalBackdrop = document.getElementById('molecule-modal-backdrop');
  btnCloseMol?.addEventListener('click', closeMoleculeModal);
  modalBackdrop?.addEventListener('click', (e) => {
    if (e.target === modalBackdrop) closeMoleculeModal();
  });

  // Setup educational info panel interactions & scroll cue
  setupInfoPanelInteractions();
}

function setupInfoPanelInteractions() {
  const card = document.getElementById('stage-card');
  const btnScrollCue = document.getElementById('btn-scroll-down-cue');

  // Floating scroll cue button click smoothly scrolls down panel
  btnScrollCue?.addEventListener('click', () => {
    if (card) {
      card.scrollBy({ top: 180, behavior: 'smooth' });
    }
  });

  // Listen for scroll events on educational card to update scroll cue badge
  card?.addEventListener('scroll', updatePanelScrollCue, { passive: true });
  window.addEventListener('resize', updatePanelScrollCue, { passive: true });

  // Initial status check
  setTimeout(updatePanelScrollCue, 150);
}

export function updatePanelScrollCue() {
  const card = document.getElementById('stage-card');
  const cue = document.getElementById('panel-scroll-cue');
  if (!card || !cue) return;

  const canScroll = card.scrollHeight > card.clientHeight + 16;
  const isNearBottom = card.scrollTop + card.clientHeight >= card.scrollHeight - 24;

  if (canScroll && !isNearBottom) {
    cue.classList.add('is-visible');
  } else {
    cue.classList.remove('is-visible');
  }
}

// =============================================================================
// 5. BOTTOM PROCESS BAR INITIALIZATION & COORDINATION (Section §3)
// =============================================================================

function initBottomProcessBar() {
  const container = document.getElementById('process-nodes-container');
  if (!container) return;
  container.innerHTML = '';

  STAGES_DATA.forEach((stage, idx) => {
    const nodeBtn = document.createElement('button');
    nodeBtn.className = `process-node ${idx === 0 ? 'active' : ''}`;
    nodeBtn.setAttribute('data-stage', idx);
    nodeBtn.setAttribute('title', `Jump to ${stage.number}: ${stage.title}`);

    nodeBtn.innerHTML = `
      <div class="node-icon-circle">${stage.iconLabel || stage.number.split(' ')[0]}</div>
      <div class="node-label-group">
        <span class="node-step-num">${stage.number.split(' ')[0]}</span>
        <span class="node-step-name">${stage.shortName}</span>
      </div>
    `;

    nodeBtn.addEventListener('click', () => goToStage(idx));
    container.appendChild(nodeBtn);
  });
}

export function goToStage(stageIndex) {
  if (stageIndex < 0 || stageIndex >= STAGES_DATA.length) return;
  state.currentStage = stageIndex;
  renderStage(stageIndex);
  render2DStage(stageIndex);
}

function renderStage(stageIndex) {
  const stage = STAGES_DATA[stageIndex];
  if (!stage) return;

  // 1. Update Card Headers & Badges
  setText('stage-number-tag', `STAGE ${stage.number}`);
  setText('badge-compartment', stage.compartment);
  setText('badge-nature', stage.nature);
  setText('stage-title', stage.title);
  setText('stage-concept', stage.conceptHeadline);

  // 2. Educational UX 4-Pack (Where / What / How / Why)
  setText('anchor-where', stage.where);
  setText('anchor-what', stage.what);
  setText('anchor-how', stage.how);
  setText('anchor-why', stage.why);

  // Trigger fresh slide-down animation on anchor text
  ['anchor-where', 'anchor-what', 'anchor-how', 'anchor-why'].forEach(id => {
    const el = document.getElementById(id);
    if (el) {
      el.classList.remove('slide-down-fresh');
      void el.offsetWidth;
      el.classList.add('slide-down-fresh');
    }
  });

  // Reset card scroll position to top and update scroll cue
  const card = document.getElementById('stage-card');
  if (card) {
    card.scrollTop = 0;
  }
  setTimeout(updatePanelScrollCue, 100);

  // 3. Molecules in Focus Chips
  const molContainer = document.getElementById('stage-molecules-list');
  if (molContainer) {
    molContainer.innerHTML = '';
    stage.moleculesInFocus.forEach(molKey => {
      const molData = MOLECULES_DATA[molKey];
      if (!molData) return;
      const chip = document.createElement('button');
      chip.className = 'mol-chip';
      chip.textContent = molData.name;
      chip.addEventListener('click', () => openMoleculeModal(molKey));
      molContainer.appendChild(chip);
    });
  }

  // 5. Deeper Accordion Content
  const deeperBody = document.getElementById('deeper-body-text');
  if (deeperBody && stage.deeper) {
    deeperBody.innerHTML = `
      <h5>Enzymology &amp; Coenzymes</h5>
      <p>${stage.deeper.enzymology}</p>
      
      <h5>Chemical Mechanism</h5>
      <p>${stage.deeper.mechanism}</p>
      
      <h5>Metabolic Regulation</h5>
      <p>${stage.deeper.regulation}</p>
      
      <div class="deeper-note">
        <strong>Pedagogical Mechanism Note:</strong> ${stage.deeper.simplificationNote}
      </div>
    `;
  }

  // 6. Navigation Buttons on Card and Process Bar
  const btnPrev = document.getElementById('btn-prev-stage');
  const btnNext = document.getElementById('btn-next-stage');
  const btnBarPrev = document.getElementById('btn-process-prev');
  const btnBarNext = document.getElementById('btn-process-next');
  
  const isFirst = (stageIndex === 0);
  const isLast = (stageIndex === STAGES_DATA.length - 1);

  if (btnPrev) btnPrev.disabled = isFirst;
  if (btnNext) btnNext.disabled = isLast;
  if (btnBarPrev) btnBarPrev.disabled = isFirst;
  if (btnBarNext) btnBarNext.disabled = isLast;

  // 7. Update Bottom Process Bar Nodes & Progress Fill Line
  const allNodes = document.querySelectorAll('.process-node');
  allNodes.forEach((node, idx) => {
    node.classList.remove('active', 'completed');
    if (idx === stageIndex) {
      node.classList.add('active');
    } else if (idx < stageIndex) {
      node.classList.add('completed');
    }
  });

  const progressFill = document.getElementById('process-track-fill');
  if (progressFill) {
    const pct = (stageIndex / (STAGES_DATA.length - 1)) * 100;
    progressFill.style.width = `${pct}%`;
  }

  // 8. Update Carbon Tracker
  updateCarbonTracker(stage.carbonState);

  // 9. Update Focus Pill in Scene Header
  setText('stage-focus-name', getStageFocusName(stageIndex));
}

// =============================================================================
// 6. CARBON TRACKER LOGIC
// =============================================================================

function updateCarbonTracker(carbonState) {
  if (!carbonState) return;
  setText('carbon-status', carbonState.status);
  const statusEl = document.getElementById('carbon-status');
  if (statusEl) statusEl.title = `Carbon Fate: ${carbonState.status}`;

  const b1 = document.getElementById('c-bead-1');
  const b2 = document.getElementById('c-bead-2');
  const b3 = document.getElementById('c-bead-3');
  
  const beads = [b1, b2, b3];
  carbonState.beads.forEach((stateName, idx) => {
    if (beads[idx]) {
      beads[idx].className = `c-bead ${stateName}`;
    }
  });

  syncHeaderHeight();
  updateHeaderScrollCues();
}

// =============================================================================
// 7. TOGGLES: ALL LABELS & PER-GLUCOSE STOICHIOMETRY
// =============================================================================

function toggleLabels() {
  state.showAllLabels = !state.showAllLabels;
  const btn = document.getElementById('btn-toggle-labels');
  const statusText = document.getElementById('lbl-status-text');
  
  if (btn) btn.setAttribute('aria-pressed', state.showAllLabels.toString());
  if (statusText) statusText.textContent = state.showAllLabels ? 'All On' : 'Default';
  
  toggleAll2DLabels(state.showAllLabels);
}

function toggleGlucoseYield() {
  state.perGlucoseMode = !state.perGlucoseMode;
  const btn = document.getElementById('btn-toggle-glucose');
  const yieldText = document.getElementById('yield-mode-text');
  const badge = document.getElementById('stoichiometry-badge');
  const eqChem = document.getElementById('hud-equation');
  
  if (btn) btn.setAttribute('aria-pressed', state.perGlucoseMode.toString());
  
  const stoichFactors = document.querySelectorAll('.stoich-factor');
  
  if (state.perGlucoseMode) {
    if (yieldText) yieldText.textContent = '2× GLUCOSE';
    if (badge) badge.textContent = '2× GLUCOSE';
    if (eqChem) {
      eqChem.innerHTML = `
        <span class="m-react">2 pyruvate</span> + <span class="m-react">2 CoA</span> + <span class="m-react">2 NAD⁺</span>
        <span class="eq-arrow">&rarr;</span>
        <span class="m-prod">2 acetyl-CoA</span> + <span class="m-prod">2 CO₂</span> + <span class="m-prod">2 NADH</span> + <span class="m-prod">2 H⁺</span>
      `;
    }
    stoichFactors.forEach(el => { el.textContent = '2×'; });
  } else {
    if (yieldText) yieldText.textContent = '1× PYRUVATE';
    if (badge) badge.textContent = '1× PYRUVATE';
    if (eqChem) {
      eqChem.innerHTML = `
        <span class="m-react">pyruvate</span> + <span class="m-react">CoA</span> + <span class="m-react">NAD⁺</span>
        <span class="eq-arrow">&rarr;</span>
        <span class="m-prod">acetyl-CoA</span> + <span class="m-prod">CO₂</span> + <span class="m-prod">NADH</span> + <span class="m-prod">H⁺</span>
      `;
    }
    stoichFactors.forEach(el => { el.textContent = '1×'; });
  }

  syncHeaderHeight();
  updateHeaderScrollCues();
}

function toggleDeeperAccordion() {
  state.isDeeperOpen = !state.isDeeperOpen;
  const btn = document.getElementById('btn-deeper-toggle');
  const content = document.getElementById('deeper-content');
  
  if (btn) btn.setAttribute('aria-expanded', state.isDeeperOpen.toString());
  if (content) content.hidden = !state.isDeeperOpen;
  setTimeout(updatePanelScrollCue, 100);
}

// =============================================================================
// 8. MOLECULE INSPECTOR MODAL
// =============================================================================

export function openMoleculeModal(molKey) {
  const mol = MOLECULES_DATA[molKey];
  if (!mol) return;

  setText('modal-mol-name', mol.name);
  setText('modal-mol-formula', mol.formula);
  setText('modal-mol-cat', mol.category);
  setText('modal-mol-carbons', mol.carbons.toString());
  setText('modal-mol-role', mol.role);
  setText('modal-mol-fate', mol.fate);

  const diag = document.getElementById('modal-mol-diagram');
  if (diag) diag.textContent = mol.diagram;

  const alertBox = document.getElementById('modal-mol-alert');
  if (alertBox) {
    alertBox.innerHTML = `<strong>Key Syllabus Note:</strong> ${mol.alert}`;
  }

  const backdrop = document.getElementById('molecule-modal-backdrop');
  if (backdrop) backdrop.hidden = false;
}

function closeMoleculeModal() {
  const backdrop = document.getElementById('molecule-modal-backdrop');
  if (backdrop) backdrop.hidden = true;
}

function setText(id, txt) {
  const el = document.getElementById(id);
  if (el) el.textContent = txt;
}
